-- AlterTable
ALTER TABLE "WeeklyPlan" ADD COLUMN     "isPlus1" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isPlus2" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isPlus3" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "location1" TEXT,
ADD COLUMN     "location2" TEXT,
ADD COLUMN     "location3" TEXT,
ADD COLUMN     "mealCheck1" TEXT,
ADD COLUMN     "mealCheck2" TEXT,
ADD COLUMN     "mealCheck3" TEXT,
ADD COLUMN     "meetDate1" TEXT,
ADD COLUMN     "meetDate2" TEXT,
ADD COLUMN     "meetDate3" TEXT,
ADD COLUMN     "meetTime1" TEXT,
ADD COLUMN     "meetTime2" TEXT,
ADD COLUMN     "meetTime3" TEXT,
ADD COLUMN     "myBusiness1" TEXT,
ADD COLUMN     "myBusiness2" TEXT,
ADD COLUMN     "myBusiness3" TEXT,
ADD COLUMN     "name1" TEXT,
ADD COLUMN     "name2" TEXT,
ADD COLUMN     "name3" TEXT,
ADD COLUMN     "phone1" TEXT,
ADD COLUMN     "phone2" TEXT,
ADD COLUMN     "phone3" TEXT,
ADD COLUMN     "purpose1" TEXT,
ADD COLUMN     "purpose2" TEXT,
ADD COLUMN     "purpose3" TEXT,
ADD COLUMN     "theirBusiness1" TEXT,
ADD COLUMN     "theirBusiness2" TEXT,
ADD COLUMN     "theirBusiness3" TEXT,
ADD COLUMN     "theirInterest1" TEXT,
ADD COLUMN     "theirInterest2" TEXT,
ADD COLUMN     "theirInterest3" TEXT;
